### ISSUE TITLE
OOM when evaluate_dtu_mesh

### ISSUE THREAD

**Issue by fangchuan** [autonomousvision/gaussian-opacity-fields#21]
Hi, thanks for your wonderful work!
I'm trying to repeat the quantitative results in your paper on a single A100 GPU. I am able to generate the tsdf fusion mesh in voxel_size=0.002, but I fail to run evaluate_dtu_mesh.py and was killed in the `cull_mesh()` function:
https://github.com/autonomousvision/gaussian-opacity-fields/blob/c3b4c9ee75866bedcca1d7b2b4dac31aee20be59/evaluate_dtu_mesh.py#L134

It takes over 1000 RAM and then is killed. Could you give me some suggestion or solution for this problem? @niujinshuchong 
Thanks in advance!

**Comment by ruili3** [comment]
> Hi, thanks for your wonderful work! I'm trying to repeat the quantitative results in your paper on a single A100 GPU. I am able to generate the tsdf fusion mesh in voxel_size=0.002, but I fail to run evaluate_dtu_mesh.py and was killed in the `cull_mesh()` function:
> 
> https://github.com/autonomousvision/gaussian-opacity-fields/blob/c3b4c9ee75866bedcca1d7b2b4dac31aee20be59/evaluate_dtu_mesh.py#L134
> 
> It takes over 1000 RAM and then is killed. Could you give me some suggestion or solution for this problem? @niujinshuchong Thanks in advance!

Hi,

How do you manage loading `dtu_cameras` and `gt_points` here
https://github.com/autonomousvision/gaussian-opacity-fields/blob/c3b4c9ee75866bedcca1d7b2b4dac31aee20be59/evaluate_dtu_mesh.py#L148
I can't find the corresponding files required in `load_dtu_camera`. How do you solve this? I can not run to your position otherwise we can take a look at it together.

**Comment by fangchuan** [comment]
> > Hi, thanks for your wonderful work! I'm trying to repeat the quantitative results in your paper on a single A100 GPU. I am able to generate the tsdf fusion mesh in voxel_size=0.002, but I fail to run evaluate_dtu_mesh.py and was killed in the `cull_mesh()` function:
> > https://github.com/autonomousvision/gaussian-opacity-fields/blob/c3b4c9ee75866bedcca1d7b2b4dac31aee20be59/evaluate_dtu_mesh.py#L134
> > 
> > It takes over 1000 RAM and then is killed. Could you give me some suggestion or solution for this problem? @niujinshuchong Thanks in advance!
> 
> Hi,
> 
> How do you manage loading `dtu_cameras` and `gt_points` here
> 
> https://github.com/autonomousvision/gaussian-opacity-fields/blob/c3b4c9ee75866bedcca1d7b2b4dac31aee20be59/evaluate_dtu_mesh.py#L148
> 
> 
> I can't find the corresponding files required in `load_dtu_camera`. How do you solve this? I can not run to your position otherwise we can take a look at it together.

You need to download the necessary data on [DTU](http://roboimagedata2.compute.dtu.dk/data/MVS/SampleSet.zip)

**Comment by ekhaliul** [comment]
I am also getting OOM error when running a bicycle scene with A100@40Gb GPU. What is the memory requirement for this to run through ?

```
OMP_NUM_THREADS=4 CUDA_VISIBLE_DEVICES=0 python extract_mesh.py -m exp_360/release/bicycle --iteration 30000
Looking for config file in exp_360/release/bicycle/cfg_args
Config file found: exp_360/release/bicycle/cfg_args
Rendering exp_360/release/bicycle
Loading trained model at iteration 30000
Reading camera 194/194
Loading Training Cameras
Loading Test Cameras
create cells and save
Rendering progress: 100%|████████████████████████████████████████████████| 169/169 [01:30<00:00,  1.88it/s]
torch.Size([1, 49133313, 3]) torch.Size([328313742, 4]) torch.Size([49133313])
Traceback (most recent call last):
  File "extract_mesh.py", line 144, in <module>
    extract_mesh(model.extract(args), args.iteration, pipeline.extract(args))
  File "extract_mesh.py", line 127, in extract_mesh
    marching_tetrahedra_with_binary_search(dataset.model_path, "test", iteration, cams, gaussians, pipeline, background, kernel_size)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "extract_mesh.py", line 62, in marching_tetrahedra_with_binary_search
    verts_list, scale_list, faces_list, _ = marching_tetrahedra(vertices, tets, sdf, points_scale[None])
  File "/home/ekhaliullin/gaussian-opacity-fields/utils/tetmesh.py", line 189, in marching_tetrahedra
    list_of_outputs = [_unbatched_marching_tetrahedra(vertices[b], tets, sdf[b], scales[b]) for b in range(vertices.shape[0])]
  File "/home/ekhaliullin/gaussian-opacity-fields/utils/tetmesh.py", line 189, in <listcomp>
    list_of_outputs = [_unbatched_marching_tetrahedra(vertices[b], tets, sdf[b], scales[b]) for b in range(vertices.shape[0])]
  File "/home/ekhaliullin/gaussian-opacity-fields/utils/tetmesh.py", line 86, in _unbatched_marching_tetrahedra
    unique_faces_0 = idx_map[merged_faces.reshape(-1)].reshape(-1, 3)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.20 GiB (GPU 0; 39.39 GiB total capacity; 32.04 GiB already allocated; 1.72 GiB free; 35.53 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by ekhaliul** [comment]
I am also getting OOM error when running a bicycle scene with A100@40Gb GPU. What is the memory requirement for this to run through ?

```
OMP_NUM_THREADS=4 CUDA_VISIBLE_DEVICES=0 python extract_mesh.py -m exp_360/release/bicycle --iteration 30000
Looking for config file in exp_360/release/bicycle/cfg_args
Config file found: exp_360/release/bicycle/cfg_args
Rendering exp_360/release/bicycle
Loading trained model at iteration 30000
Reading camera 194/194
Loading Training Cameras
Loading Test Cameras
create cells and save
Rendering progress: 100%|████████████████████████████████████████████████| 169/169 [01:30<00:00,  1.88it/s]
torch.Size([1, 49133313, 3]) torch.Size([328313742, 4]) torch.Size([49133313])
Traceback (most recent call last):
  File "extract_mesh.py", line 144, in <module>
    extract_mesh(model.extract(args), args.iteration, pipeline.extract(args))
  File "extract_mesh.py", line 127, in extract_mesh
    marching_tetrahedra_with_binary_search(dataset.model_path, "test", iteration, cams, gaussians, pipeline, background, kernel_size)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "extract_mesh.py", line 62, in marching_tetrahedra_with_binary_search
    verts_list, scale_list, faces_list, _ = marching_tetrahedra(vertices, tets, sdf, points_scale[None])
  File "/home/user/gaussian-opacity-fields/utils/tetmesh.py", line 189, in marching_tetrahedra
    list_of_outputs = [_unbatched_marching_tetrahedra(vertices[b], tets, sdf[b], scales[b]) for b in range(vertices.shape[0])]
  File "/home/user/gaussian-opacity-fields/utils/tetmesh.py", line 189, in <listcomp>
    list_of_outputs = [_unbatched_marching_tetrahedra(vertices[b], tets, sdf[b], scales[b]) for b in range(vertices.shape[0])]
  File "/home/user/gaussian-opacity-fields/utils/tetmesh.py", line 86, in _unbatched_marching_tetrahedra
    unique_faces_0 = idx_map[merged_faces.reshape(-1)].reshape(-1, 3)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.20 GiB (GPU 0; 39.39 GiB total capacity; 32.04 GiB already allocated; 1.72 GiB free; 35.53 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by Shhfdsdf** [comment]
![image](https://github.com/autonomousvision/gaussian-opacity-fields/assets/140057828/2ca9f81b-04bc-490a-8f98-835083967466)
![image](https://github.com/autonomousvision/gaussian-opacity-fields/assets/140057828/c0dc44d2-94f7-4a32-b6dc-926829e278f4)

it seems like i get the same error,i use the uncull mesh to eval before,it's still be killed

**Comment by Shhfdsdf** [comment]
> ![image](https://private-user-images.githubusercontent.com/140057828/331844762-2ca9f81b-04bc-490a-8f98-835083967466.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMDYzNTEsIm5iZiI6MTcxNjEwNjA1MSwicGF0aCI6Ii8xNDAwNTc4MjgvMzMxODQ0NzYyLTJjYTlmODFiLTA0YmMtNDkwYS04Zjk4LTgzNTA4Mzk2NzQ2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwODA3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjQ2MmE1ODBmYThiZTM2YjVjZjIxZThiZWVkNmM1ODM4OTNjMTQ4NjUxMGI0NWNmYWIwYjg0Y2M0MmY4MTQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oUNO-bg-lGUlphkOh4jDw9pOdvihDXSNaV8TtcCIWPw) ![image](https://private-user-images.githubusercontent.com/140057828/331844841-c0dc44d2-94f7-4a32-b6dc-926829e278f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMDYzNTEsIm5iZiI6MTcxNjEwNjA1MSwicGF0aCI6Ii8xNDAwNTc4MjgvMzMxODQ0ODQxLWMwZGM0NGQyLTk0ZjctNGEzMi1iNmRjLTkyNjgyOWUyNzhmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwODA3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZWJkMmI0ZDMzOGI5M2MxMGUxZTY4ZTVlMWFlOWQ1OWFiMDhkYTFlYmI4MTY5NmU3YmNmMTBjMWJkNjYzZDZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fqpFhdFEfvdaxZloShfywdc3VdPw9clD2bEqI4cQ6nk)
> 
> it seems like i get the same error,i use the uncull mesh to eval before,it's still be killed

![image](https://github.com/autonomousvision/gaussian-opacity-fields/assets/140057828/ec7266c4-40b5-4abd-aa8f-ab5d74c2e5ce)
after i removed these few lines of code,it works!but I'm not sure if the result is accurate

python dtu_eval/eval.py --data exp_dtu/release/scan24/test/ours_30000/tsdf/tsdf_aligned.ply --scan 24 --mode mesh --dataset_dir dtu_eval/Offical_DTU_Dataset --vis_out_dir exp_dtu/release/scan24/test/ours_30000/tsdf
done: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [01:51<00:00, 12.34s/it]
0.4626517840226122 0.47273726170521585 0.467694522863914
