### ISSUE TITLE
submodules/diff-gaussian-rasterization build error, RTX 4090

### ISSUE THREAD

**Issue by Loppas** [autonomousvision/gaussian-opacity-fields#83]
Hi,

The cuda version used doesn't officially support RTX 40 series but to get around that I used: `export TORCH_CUDA_ARCH_LIST=8.6`

However, when i run `pip install submodules/diff-gaussian-rasterization` i get the following error: 

```
[5/5] /home/brandon/miniconda3/envs/gof/bin/nvcc  -I/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/torch/include -I/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/torch/include/TH -I/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/torch/include/THC -I/home/brandon/miniconda3/envs/gof/include -I/home/brandon/miniconda3/envs/gof/include/python3.8 -c -c /mnt/c/Users/eberl/Documents/github-projects/gaussian-opacity-fields/submodules/diff-gaussian-rasterization/cuda_rasterizer/rasterizer_impl.cu -o /mnt/c/Users/eberl/Documents/github-projects/gaussian-opacity-fields/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38/cuda_rasterizer/rasterizer_impl.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -Xcompiler -fno-gnu-unique -I/mnt/c/Users/eberl/Documents/github-projects/gaussian-opacity-fields/submodules/diff-gaussian-rasterization/third_party/glm/ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -ccbin /home/brandon/miniconda3/envs/gof/bin/x86_64-conda-linux-gnu-cc -std=c++14
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
          subprocess.run(
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/mnt/c/Users/eberl/Documents/github-projects/gaussian-opacity-fields/submodules/diff-gaussian-rasterization/setup.py", line 17, in <module>
          setup(
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 93, in run
          _build_ext.run(self)
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 254, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
          objects = self.compiler.compile(
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 586, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/brandon/miniconda3/envs/gof/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
```

Does anyone have any suggestions on how I can get it to build? 

I tried updating `torch` to `cu117` and updating `cudatoolkit-dev` to `11.7` without the cuda arch list workaround but I get the same error as above.

#### Runtime info
Graphics Card: `RTX 4090`
Operating System: `Ubuntu 22.04.3 LTS (Jammy Jellyfish) through WSL on Windows 11`
CUDA version: `Build cuda_11.3.r11.3/compiler.29920130_0`
C++ compiler: `x86_64-conda-linux-gnu-cc (conda-forge gcc 9.5.0-19) 9.5.0`

**Comment by niujinshuchong** [comment]
Hi, I don't have a RTX 4090 GPU but I think the code should work out of box for 4090. Could you try to install it with cuda 12.1?

**Comment by Loppas** [comment]
@niujinshuchong Thanks for the reply, I managed to get it compiling now using `cuda 12.4`. 

The issue was that i didn't have my cuda env variables setup correctly, specifically i needed to do this:
```
export CUDADIR=/usr/local/cuda-12.4
export CPATH=/usr/local/cuda-12.4/include${CPATH:+:${CPATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-12.4/lib64:${LD_LIBRARY_PATH}
ln -s /usr/include/crypt.h $CONDA_PREFIX/include/crypt.h
```
